image: Visual Studio 2015

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - set PATH=%PATH%;C:\Qt\5.9\msvc2015\bin;C:\Qt\Tools\QtCreator\bin;

install:
  # Submodules are not cloned by default
  - git submodule update --init --recursive

build_script:
  - qmake cuteproject.pro -r CONFIG+=release
  - jom
  - ps: ls $(get-location).Path -filter *.exe -recurse
