image: mxklb/docker-qt5-deb

stages:
- build
- deploy
- release

before_script:
- apt-get update -y
- apt-get install -y wget xvfb chrpath libfuse-dev

debug_tests:
  stage: build
  script:
    - qmake cuteproject.pro -r CONFIG+=debug
    - make
    - gcovr -r . -e '.*extern.*' -e '.*moc_.*'
    - chmod +x lcov.sh && ./lcov.sh
    - mv coverage/*.pdf .
    - mv coverage/*.tar.gz .
  artifacts:
    paths:
      - coverage.pdf
      - coverage.tar.gz
    name: "test_coverage"

release_tests:
  stage: build
  script:
    - qmake cuteproject.pro -r CONFIG+=release
    - make

release:
  stage: build
  script:
    - echo "catchTests=false" > globals.pri
    - qmake cuteproject.pro -r CONFIG+=release
    - make

deploy_appimage:
  stage: deploy
  image: mxklb/docker-qt5-deb:trusty
  only:
    - master
  script:
    - echo "catchTests=false" > globals.pri
    - qmake cuteproject.pro -r CONFIG+=release
    - make
    - chmod +x pkgs/version.sh
    - chmod +x pkgs/appimage.sh && pkgs/appimage.sh
    - mv pkgs/cuteproject-* .
  artifacts:
    paths:
      - cuteproject-*
    name: "cuteproject-x86_64"

release_appimage:
  stage: deploy
  image: mxklb/docker-qt5-deb:trusty
  only:
    - tags
  script:
    - echo "catchTests=false" > globals.pri
    - qmake cuteproject.pro -r CONFIG+=release
    - make
    - chmod +x pkgs/version.sh
    - chmod +x pkgs/appimage.sh && pkgs/appimage.sh
    - mv pkgs/cuteproject-* .
  artifacts:
    paths:
      - cuteproject-*
    name: "cuteproject-x86_64"

deploy_trusty:
  stage: deploy
  image: mxklb/docker-qt5-deb:trusty
  only:
    - master
  script:
    - export USER=$GITLAB_USER_LOGIN
    - chmod +x pkgs/version.sh
    - chmod +x pkgs/debian.sh && pkgs/debian.sh
    - mv pkgs/deb/cuteproject-*.deb .
  artifacts:
    paths:
      - cuteproject-*.deb
    name: "cuteproject-trusty_amd64"

deploy_xenial:
  stage: deploy
  image: mxklb/docker-qt5-deb:xenial
  only:
    - master
  script:
    - chmod +x pkgs/version.sh
    - chmod +x pkgs/debian.sh && pkgs/debian.sh
    - mv pkgs/deb/cuteproject-*.deb .
  artifacts:
    paths:
      - cuteproject-*.deb
    name: "cuteproject-xenial_amd64"

publish_releases:
  stage: release
  image: inetprocess/gitlab-release
  only:
    - tags
  script:
    - gitlab-release --message 'Release $CI_COMMIT_TAG' cuteproject-*
