image: mxklb/docker-qt5-deb

stages:
- build
- deploy

before_script:
- apt-get update -y
- apt-get install -y wget xvfb chrpath

debug_tests:
  stage: build
  script:
    - qmake cuteproject.pro -r CONFIG+=debug
    - make
    - gcovr -r . -e '.*extern.*' -e '.*moc_.*'
    - chmod +x lcov.sh && ./lcov.sh
    - mv coverage/*.pdf .
    - mv coverage/*.tar.gz .
  artifacts:
    paths:
      - coverage.pdf
      - coverage.tar.gz
    name: "test_coverage"

release_tests:
  stage: build
  script:
    - qmake cuteproject.pro -r CONFIG+=release
    - make

deploy_trusty:
  stage: deploy
  image: mxklb/docker-qt5-deb:trusty
  only:
    - master
  script:
    - export USER=$GITLAB_USER_LOGIN
    - chmod +x pkgs/debian.sh && pkgs/debian.sh
    - mv pkgs/deb/app-*.deb .
  artifacts:
    paths:
      - app-*.deb
    name: "cuteproject-trusty_amd64"

deploy_xenial:
  stage: deploy
  image: mxklb/docker-qt5-deb:xenial
  only:
    - master
  script:
    - chmod +x pkgs/debian.sh && pkgs/debian.sh
    - mv pkgs/deb/app-*.deb .
  artifacts:
    paths:
      - app-*.deb
    name: "cuteproject-xenial_amd64"
