language: cpp
os:
  - linux
  - osx
sudo: required
dist: trusty  
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qt5-qmake catch ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH ; fi
script:
- qmake
- make
after_success:
  - ls -la libs/mylib && ls -la libs/mylib-test/ && ls -la libs/otherlib && ls -la libs/otherlib-test/ 
  - bash <(curl -s https://codecov.io/bash) -g /usr/include/
